
version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout 
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout 
      - run: npm run test
  analyse:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout 
      - run: npm run audit
workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - analyse:
          requires:
            - "test"
